// --- ARQUIVO JS (js/database.js) ---
// Banco de dados centralizado de produtos

const mockDatabase = [
    // --- Categoria: Dia-a-Dia (1000s) ---
    { cod: "1001", nome: "Patinho Moído", classificacao: "Dia-a-Dia" },
    { cod: "1002", nome: "Coxão Mole em Bife", classificacao: "Dia-a-Dia" },
    { cod: "1003", nome: "Acém em Cubos", classificacao: "Dia-a-Dia" },
    { cod: "1004", nome: "Peito de Frango", classificacao: "Dia-a-Dia" },
    { cod: "1005", nome: "Coxinha da Asa", classificacao: "Dia-a-Dia" },
    { cod: "1006", nome: "Linguiça Toscana", classificacao: "Dia-a-Dia" },
    { cod: "1007", nome: "Bisteca Suína", classificacao: "Dia-a-Dia" },
    { cod: "1008", nome: "Costela Suína", classificacao: "Dia-a-Dia" },
    { cod: "1009", nome: "Músculo Bovino", classificacao: "Dia-a-Dia" },
    { cod: "1010", nome: "Filé de Tilápia", classificacao: "Dia-a-Dia" },
    { cod: "1011", nome: "Fígado Bovino", classificacao: "Dia-a-Dia" },
    { cod: "1012", nome: "Pernil Suíno", classificacao: "Dia-a-Dia" },
    { cod: "1013", nome: "Linguiça Calabresa", classificacao: "Dia-a-Dia" },
    { cod: "1014", nome: "Coração de Frango", classificacao: "Dia-a-Dia" },
    { cod: "1015", nome: "Miolo de Alcatra", classificacao: "Dia-a-Dia" },
    { cod: "1016", nome: "Sobrecoxa de Frango", classificacao: "Dia-a-Dia" },
    { cod: "1017", nome: "Bacon em Tiras", classificacao: "Dia-a-Dia" },
    { cod: "1018", nome: "Costela Bovina Tira", classificacao: "Dia-a-Dia" },
    { cod: "1019", nome: "Salsicha Hot Dog", classificacao: "Dia-a-Dia" },
    { cod: "1020", nome: "Paleta Bovina", classificacao: "Dia-a-Dia" },

    // --- Categoria: La Reina (2000s) ---
    { cod: "2001", nome: "Picanha La Reina", classificacao: "La Reina" },
    { cod: "2002", nome: "Chorizo La Reina", classificacao: "La Reina" },
    { cod: "2003", nome: "Ancho La Reina", classificacao: "La Reina" },
    { cod: "2004", nome: "Maminha La Reina", classificacao: "La Reina" },
    { cod: "2005", nome: "Shoulder La Reina", classificacao: "La Reina" },
    { cod: "2006", nome: "Costela Tira La Reina", classificacao: "La Reina" },
    { cod: "2007", nome: "Fraldinha La Reina", classificacao: "La Reina" },
    { cod: "2008", nome: "T-Bone La Reina", classificacao: "La Reina" },
    { cod: "2009", nome: "Tomahawk La Reina", classificacao: "La Reina" },
    { cod: "2010", nome: "Prime Rib La Reina", classificacao: "La Reina" },
    { cod: "2011", nome: "Assado de Tira La Reina", classificacao: "La Reina" },
    { cod: "2012", nome: "Bife de Vazio La Reina", classificacao: "La Reina" },
    { cod: "2013", nome: "Short Rib La Reina", classificacao: "La Reina" },
    { cod: "2014", nome: "Cupim La Reina", classificacao: "La Reina" },
    { cod: "2015", nome: "Brisket La Reina", classificacao: "La Reina" },
    { cod: "2016", nome: "Flat Iron La Reina", classificacao: "La Reina" },
    { cod: "2017", nome: "Picanha Suína La Reina", classificacao: "La Reina" },
    { cod: "2018", nome: "Carré de Cordeiro La Reina", classificacao: "La Reina" },
    { cod: "2019", nome: "Short Rib Suíno La Reina", classificacao: "La Reina" },
    { cod: "2020", nome: "Denver Steak La Reina", classificacao: "La Reina" },

    // --- Categoria: La Majestad (3000s) ---
    { cod: "3001", nome: "Picanha La Majestad", classificacao: "La Majestad" },
    { cod: "3002", nome: "Chorizo La Majestad", classificacao: "La Majestad" },
    { cod: "3003", nome: "Ancho La Majestad", classificacao: "La Majestad" },
    { cod: "3004", nome: "Maminha La Majestad", classificacao: "La Majestad" },
    { cod: "3005", nome: "Shoulder La Majestad", classificacao: "La Majestad" },
    { cod: "3006", nome: "Costela Tira La Majestad", classificacao: "La Majestad" },
    { cod: "3007", nome: "Fraldinha La Majestad", classificacao: "La Majestad" },
    { cod: "3008", nome: "T-Bone La Majestad", classificacao: "La Majestad" },
    { cod: "3009", nome: "Tomahawk La Majestad", classificacao: "La Majestad" },
    { cod: "3010", nome: "Prime Rib La Majestad", classificacao: "La Majestad" },
    { cod: "3011", nome: "Assado de Tira La Majestad", classificacao: "La Majestad" },
    { cod: "3012", nome: "Bife de Vazio La Majestad", classificacao: "La Majestad" },
    { cod: "3013", nome: "Short Rib La Majestad", classificacao: "La Majestad" },
    { cod: "3014", nome: "Cupim La Majestad", classificacao: "La Majestad" },
    { cod: "3015", nome: "Brisket La Majestad", classificacao: "La Majestad" },
    { cod: "3016", nome: "Flat Iron La Majestad", classificacao: "La Majestad" },
    { cod: "3017", nome: "Picanha Suína La Majestad", classificacao: "La Majestad" },
    { cod: "3018", nome: "Carré de Cordeiro La Majestad", classificacao: "La Majestad" },
    { cod: "3019", nome: "Short Rib Suíno La Majestad", classificacao: "La Majestad" },
    { cod: "3020", nome: "Denver Steak La Majestad", classificacao: "La Majestad" },

    // --- Categoria: Codigo Series (4000s) ---
    { cod: "4001", nome: "Picanha Codigo Series", classificacao: "Codigo Series" },
    { cod: "4002", nome: "Chorizo Codigo Series", classificacao: "Codigo Series" },
    { cod: "4003", nome: "Ancho Codigo Series", classificacao: "Codigo Series" },
    { cod: "4004", nome: "Maminha Codigo Series", classificacao: "Codigo Series" },
    { cod: "4005", nome: "Shoulder Codigo Series", classificacao: "Codigo Series" },
    { cod: "4006", nome: "Costela Tira Codigo Series", classificacao: "Codigo Series" },
    { cod: "4007", nome: "Fraldinha Codigo Series", classificacao: "Codigo Series" },
    { cod: "4008", nome: "T-Bone Codigo Series", classificacao: "Codigo Series" },
    { cod: "4009", nome: "Tomahawk Codigo Series", classificacao: "Codigo Series" },
    { cod: "4010", nome: "Prime Rib Codigo Series", classificacao: "Codigo Series" },
    { cod: "4011", nome: "Assado de Tira Codigo Series", classificacao: "Codigo Series" },
    { cod: "4012", nome: "Bife de Vazio Codigo Series", classificacao: "Codigo Series" },
    { cod: "4013", nome: "Short Rib Codigo Series", classificacao: "Codigo Series" },
    { cod: "4014", nome: "Cupim Codigo Series", classificacao: "Codigo Series" },
    { cod: "4015", nome: "Brisket Codigo Series", classificacao: "Codigo Series" },
    { cod: "4016", nome: "Flat Iron Codigo Series", classificacao: "Codigo Series" },
    { cod: "4017", nome: "Picanha Suína Codigo Series", classificacao: "Codigo Series" },
    { cod: "4018", nome: "Carré de Cordeiro Codigo Series", classificacao: "Codigo Series" },
    { cod: "4019", nome: "Short Rib Suíno Codigo Series", classificacao: "Codigo Series" },
    { cod: "4020", nome: "Denver Steak Codigo Series", classificacao: "Codigo Series" },

    // --- Categoria: Itens Secos (5000s) ---
    { cod: "5001", nome: "Sal Grosso", classificacao: "Itens Secos" },
    { cod: "5002", nome: "Sal de Parrilla", classificacao: "Itens Secos" },
    { cod: "5003", nome: "Farinha de Mandioca", classificacao: "Itens Secos" },
    { cod: "5004", nome: "Farofa Pronta", classificacao: "Itens Secos" },
    { cod: "5005", nome: "Tempero Chimichurri", classificacao: "Itens Secos" },
    { cod: "5006", nome: "Molho Barbecue", classificacao: "Itens Secos" },
    { cod: "5007", nome: "Pão de Alho", classificacao: "Itens Secos" },
    { cod: "5008", nome: "Carvão 3kg", classificacao: "Itens Secos" },
    { cod: "5009", nome: "Carvão 5kg", classificacao: "Itens Secos" },
    { cod: "5010", nome: "Lenha Frutífera", classificacao: "Itens Secos" },
    { cod: "5011", nome: "Acendedor Fogo", classificacao: "Itens Secos" },
    { cod: "5012", nome: "Azeite de Oliva", classificacao: "Itens Secos" },
    { cod: "5013", nome: "Molho de Pimenta", classificacao: "Itens Secos" },
    { cod: "5014", nome: "Dry Rub (Tempero Seco)", classificacao: "Itens Secos" },
    { cod: "5015", nome: "Alho Frito", classificacao: "Itens Secos" },
    { cod: "5016", nome: "Batata Palha", classificacao: "Itens Secos" },
    { cod: "5017", nome: "Pimenta do Reino Grãos", classificacao: "Itens Secos" },
    { cod: "5018", nome: "Palmito Pupunha", classificacao: "Itens Secos" },
    { cod: "5019", nome: "Azeitona Verde", classificacao: "Itens Secos" },
    { cod: "5020", nome: "Geleia de Pimenta", classificacao: "Itens Secos" },

    // --- Categoria: Bebidas (6000s) ---
    { cod: "6001", nome: "Água Mineral com Gás", classificacao: "Bebidas" },
    { cod: "6002", nome: "Água Mineral sem Gás", classificacao: "Bebidas" },
    { cod: "6003", nome: "Coca-Cola Lata", classificacao: "Bebidas" },
    { cod: "6004", nome: "Coca-Cola Zero Lata", classificacao: "Bebidas" },
    { cod: "6005", nome: "Guaraná Antarctica Lata", classificacao: "Bebidas" },
    { cod: "6006", nome: "Guaraná Zero Lata", classificacao: "Bebidas" },
    { cod: "6007", nome: "Cerveja Pilsen Long Neck", classificacao: "Bebidas" },
    { cod: "6008", nome: "Cerveja IPA Long Neck", classificacao: "Bebidas" },
    { cod: "6009", nome: "Cerveja Trigo Long Neck", classificacao: "Bebidas" },
    { cod: "6010", nome: "Energético Red Bull", classificacao: "Bebidas" },
    { cod: "6011", nome: "Suco Laranja Integral 1L", classificacao: "Bebidas" },
    { cod: "6G12", nome: "Suco Uva Integral 1L", classificacao: "Bebidas" },
    { cod: "6013", nome: "Vinho Tinto Malbec", classificacao: "Bebidas" },
    { cod: "6014", nome: "Vinho Tinto Cabernet", classificacao: "Bebidas" },
    { cod: "6015", nome: "Vinho Branco Sauvignon", classificacao: "Bebidas" },
    { cod: "6016", nome: "Whisky Jack Daniels", classificacao: "Bebidas" },
    { cod: "6017", nome: "Gin Importado", classificacao: "Bebidas" },
    { cod: "6018", nome: "Água Tônica Lata", classificacao: "Bebidas" },
    { cod: "6019", nome: "H2OH! Limoneto", classificacao: "Bebidas" },
    { cod: "6020", nome: "Chá Gelado Limão", classificacao: "Bebidas" },

    // --- Categoria: Diversos (7000s) ---
    { cod: "7001", nome: "Embalagem P", classificacao: "Diversos" },
    { cod: "7002", nome: "Embalagem M", classificacao: "Diversos" },
    { cod: "7003", nome: "Embalagem G", classificacao: "Diversos" },
    { cod: "7004", nome: "Sacola Plástica", classificacao: "Diversos" },
    { cod: "7005", nome: "Guardanapo Papel", classificacao: "Diversos" },
    { cod: "7006", nome: "Papel Alumínio", classificacao: "Diversos" },
    { cod: "7007", nome: "Filme PVC", classificacao: "Diversos" },
    { cod: "7008", nome: "Copo Descartável", classificacao: "Diversos" },
    { cod: "7009", nome: "Talher Descartável", classificacao: "Diversos" },
    { cod: "7010", nome: "Prato Descartável", classificacao: "Diversos" },
    { cod: "7011", nome: "Queijo Coalho", classificacao: "Diversos" },
    { cod: "7J12", nome: "Manteiga Aviação", classificacao: "Diversos" },
    { cod: "7013", nome: "Pão de Forma", classificacao: "Diversos" },
    { cod: "7014", nome: "Gelo Cubo 5kg", classificacao: "Diversos" },
    { cod: "7015", nome: "Gelo Triturado 5kg", classificacao: "Diversos" },
    { cod: "7016", nome: "Sobremesa Pudim", classificacao: "Diversos" },
    { cod: "7017", nome: "Sobremesa Mousse", classificacao: "Diversos" },
    { cod: "7018", nome: "Saco de Lixo 100L", classificacao: "Diversos" },
    { cod: "7019", nome: "Detergente Neutro", classificacao: "Diversos" },
    { cod: "7020", nome: "Álcool 70%", classificacao: "Diversos" }
];